"use client";

import { normalize } from "./game/[gameSlug]/fetchData";
import { Inter } from "next/font/google";
import SearchBar from "@/components/searchBar";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import "@/app/globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [searchText, setSearchText] = useState(null);
  const router = useRouter();

  useEffect(() => {}, [searchText]);  

  function handleSubmit(e) {
    let search = normalize(e.target.elements.search.value);
    e.preventDefault();
    if (search !== searchText && search !== "") {
      setSearchText(search);
      router.push(`/game/${search}`, undefined, { shallow: true });
      window.history.replaceState("", "", `/game/${search}`);
    }
  }

  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <nav className="sticky top-0 z-10 backdrop-blur-lg bg-white/1 p-4">
          <SearchBar
            name={"search"}
            placeholder="Search anything ..."
            searchButtonText={"search"}
            formClass={"z-10"}
            onSubmit={handleSubmit}
          />
        </nav>
        {children}
      </body>
    </html>
  );
}
